name: Build & Push Docker Image to ECR

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/iss_tracker:${{ github.sha }}


      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body file://.github/cloudformation/ecs-fargate-deployment.yaml
        continue-on-error: false
      
      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: iss-tracker-stack
          template: .github/cloudformation/ecs-fargate-deployment.yaml
          tags: "[{\"Key\": \"GitHubSHA\", \"Value\": \"${{ github.sha }}\"}]"
          capabilities: CAPABILITY_IAM
          no-fail-on-empty-changeset: "1"





      
